### ISSUE TITLE
dataGrid 實現

### ISSUE THREAD

**Issue by raindy29** [SBDavid/flutter_sliver_tracker#1]
您好，想請教一個非關這個widget的問題，如果希望做一個dataGrid 
固定左邊的某幾個欄位不動，而能左右滑動部份內容，像以下範例
https://adazzle.github.io/react-data-grid/docs/examples/frozen-columns
不曉得在flutter 目前提供的widget 是否有辦法達成?
謝謝

**Comment by SBDavid** [comment]
我也没找到现成的，
